name: Reusable deploy
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of de deployment artifcat files
        required: false
        default: dist
        type: string
    outputs:
      result: 
        description: The result of deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  build:
    outputs: 
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Result
        run: "::set-output name=step-result::seccess"